Feature optional profiling include paths
epiforecasts/epinowcast pull request #54
Opened 2022-05-10 10:12 UTC by adrian-lison

This PR extends the optional profiling also to .stan files in the include paths, and moves the whole functionality to a separate function which is called by `enw_model` if required. All manipulated .stan files with profiling statements removed are stored in the same temporary directory.

Implementation details: By using the same folder structure in the temporary directory as in the original include paths, the relative include paths still apply and the model code is not further touched aside from removing the profiling. This should make the approach very robust. Also, the names of the main model and the included file paths are now directly mirrored, so that warnings or errors from stanc stating a filepath allow the user to pinpoint the corresponding original .stan file.

This PR also adds more detailed profiling statements to the likelihood parts of the model.

2022-05-10 10:16 UTC, adrian-lison commented on inst/stan/functions/obs_lpmf.stan
> +      tar_obs, ref_lh_i, rdlh, ref_p
The reference day effects allocation was moved out of the `expected_obs` call to be able to profile it independently.

2022-05-16 13:53 UTC, seabbs requested changes
This looks really nice and as I send before worth considering for an upstream contribution to cmsdstanr. I have some very boring style points and would like the linting sorted out 😄

2022-05-18 07:30 UTC, adrian-lison commented
Thanks for reviewing @seabbs :) I have improved the formatting as suggested. Will consider proposing it to `cmdstanr` also :)

2022-05-19 14:16 UTC, seabbs commented
/rebase

2022-05-19 14:18 UTC, seabbs commented
/rebase

2022-05-19 14:25 UTC, seabbs commented
/document

2022-05-19 14:26 UTC, seabbs approved these changes
LGTM to me. Just updating the docs and then will merge (and add news etc direct to master).

2022-05-19 14:35 UTC, merged